### ISSUE TITLE
实现简单的仿微信UI方便进行测试

### ISSUE THREAD

**Issue by jcai** [wechaty/scala-wechaty#13]
目前单元测试是个问题，考虑是否制作简单仿微信UI来进行测试功能。

**Comment by jcai** [comment]
如果后端能够一套完整的GRPC Server的mock就好了。

**Comment by huan** [comment]
The unit testing is very important for all Wechaty projects and the mock system will be a great help for the unit testings.

I like your idea of doing mock tasks from the central GRPC service. Could you please submit an RFC to draft the design of what you want to do with the mock system in detail so that we can continue discussing the mock use cases based on that?

**Comment by jcai** [comment]
Grpc 我以前没用过，不是很了解，刚看到能够自动生成测试使用的mock. https://grpc.github.io/grpc/cpp/md_doc_unit_testing.html

最近尝试尝试

**Comment by jcai** [comment]
see   570c7ca  完美实现对服务器的mock，帅！！！
